import os

SECRET_KEY=os.environ['SECRET_KEY']
DB_USERNAME=os.environ['DB_USERNAME']
DB_PASSWORD=os.environ['DB_PASSWORD']
DB_HOST=os.environ['DB_HOST']
DATABASE_NAME=os.environ['DATABASE_NAME']
DB_URI = "mysql+mysqldb://%s:%s@%s:3306/%s" % (DB_USERNAME, DB_PASSWORD, DB_HOST, DATABASE_NAME)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True
MYSQL_ROOT_PASSWORD=os.environ['MYSQL_ROOT_PASSWORD']
BLOG_NAME=os.environ['BLOG_NAME']
BLOG_POST_IMAGES_PATH=os.environ['BLOG_POST_IMAGES_PATH']
MAIL_SERVER=os.environ['MAIL_SERVER']
MAIL_PORT=os.environ['MAIL_PORT']
MAIL_USERNAME=os.environ['MAIL_USERNAME']
MAIL_PASSWORD=os.environ['MAIL_PASSWORD']
MAIL_USE_TLS=os.environ['MAIL_USE_TLS']
MAIL_USE_SSL=os.environ['MAIL_USE_SSL']

mail_settings = {
    "MAIL_SERVER": 'smtp.gmail.com',
    "MAIL_PORT": 465,
    "MAIL_USE_TLS": False,
    "MAIL_USE_SSL": True,
    "MAIL_USERNAME": MAIL_USERNAME,
    "MAIL_PASSWORD": MAIL_PASSWORD
}